#!/bin/bash
if [ $# -lt 3 ] 
then
	echo "usage: $0 <file_perm> <dir_perm> <dir1> [<dir2> ...]"
	exit 1
fi

if [ ! -d "$3" ]
then
	echo "third argument must be a directory"
	exit 2
fi

loop="1"

for param
do
	if (( loop == 1 || loop == 2))
	then
		(( loop += 1 ))
		continue
	fi

	chmod $2 "$param"

	for obj in "$param"/*
	do
		if [ -d "$obj" ]
		then
			chmod $2 "$obj"
			$0 $1 $2 "$obj"
		elif [ -f "$obj" ]
		then
			chmod $1 "$obj"
		else
			echo "unknown object: $obj"
		fi
	done
done
