#!/bin/bash
# Eigene öffentliche IP anzeigen

EXTIP=$(curl -s http://checkip.dyndns.org/ | grep -Eo '\<[[:digit:]]{1,3}(\.[[:digit:]]{1,3}){3}\>')
WHOIS=$(whois "$EXTIP")

echo "IP: $EXTIP"
echo "$WHOIS" | grep -m1 descr
echo "$WHOIS" | grep address
