#!/bin/bash
if [ -f ./openvpn.zip ]
then
    rm ./openvpn.zip
    echo deleted openvpn.zip
fi

if [ -d ./pia ]
then
    rm -r ./pia
    echo deleted pia folder
fi
wget https://www.privateinternetaccess.com/openvpn/openvpn.zip &> /dev/null
echo downloaded openvpn.zip
unzip -q openvpn.zip -d ./pia
echo unzipped openvpn.zip
cd ./pia
cat pia-username.txt > pia.key
cat pia-password.txt >> pia.key
echo created password file
find . -iname "*.ovpn" -exec gsed -i "s/auth-user-pass/auth-user-pass pia.key/g" {} \;
echo added username to ovpn files
